import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Float, Text, DateTime, JSON, Integer, ForeignKey, Index
from sqlalchemy.orm import relationship
from app.core.database import Base


class AnalyticsFinding(Base):
    """
    Persistent supervisory findings generated by the security analytics and data quality engine:
    ANOMALY, SOURCE_GAP, VOLUME_SPIKE, VOLUME_DROP, COVERAGE_GAP, CORRELATION, DATA_QUALITY, UNKNOWN_FORMAT, PARSER_FAILURE.
    """
    __tablename__ = "analytics_findings"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    finding_type = Column(String(64), nullable=False, index=True)
    severity = Column(String(32), nullable=False, index=True)  # CRITICAL, HIGH, MEDIUM, LOW
    confidence = Column(Float, nullable=False, default=0.5)  # 0.0 to 1.0
    priority_score = Column(Float, nullable=False, default=50.0, index=True)  # 0.0 to 100.0
    priority_category = Column(String(32), nullable=False, default="MEDIUM", index=True)  # CRITICAL, HIGH, MEDIUM, LOW

    source_id = Column(String(64), nullable=True, index=True)
    event_count = Column(Integer, nullable=False, default=1)
    first_seen = Column(DateTime(timezone=True), nullable=False, index=True)
    last_seen = Column(DateTime(timezone=True), nullable=False, index=True)

    title = Column(String(255), nullable=False)
    explanation = Column(Text, nullable=False)
    evidence = Column(JSON, nullable=False, default=dict)
    recommended_action = Column(Text, nullable=True)

    status = Column(String(32), nullable=False, default="OPEN", index=True)  # OPEN, REVIEWED, DISMISSED
    reviewed_by = Column(String(128), nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("ix_analytics_findings_type_status", "finding_type", "status"),
        Index("ix_analytics_findings_priority_status", "priority_score", "status"),
    )


class SourceBaseline(Base):
    """
    Historical volume and distribution baseline metrics per log source.
    """
    __tablename__ = "source_baselines"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    source_id = Column(String(64), unique=True, nullable=False, index=True)

    avg_hourly_volume = Column(Float, nullable=False, default=0.0)
    median_hourly_volume = Column(Float, nullable=False, default=0.0)
    stddev_hourly_volume = Column(Float, nullable=False, default=0.0)

    severity_distribution = Column(JSON, nullable=False, default=dict)
    protocol_distribution = Column(JSON, nullable=False, default=dict)
    action_distribution = Column(JSON, nullable=False, default=dict)

    sample_hours_count = Column(Integer, nullable=False, default=0)
    calculated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)
