from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ParsedEvent(BaseModel):
    """
    Intermediate extracted event representation generated by parsers.
    Completely decoupled from database persistence models.
    """
    extracted_fields: Dict[str, Any] = Field(default_factory=dict, description="Primary mapped key-value attributes")
    parser_id: str = Field(..., description="Unique identifier of parser utilized")
    parser_version: str = Field(default="1.0.0", description="Version of parser executed")
    source_format: str = Field(..., description="Format parsed (syslog, json, csv, cef, leef, xml)")
    warnings: List[str] = Field(default_factory=list, description="Non-fatal parsing warnings")
    errors: List[str] = Field(default_factory=list, description="Fatal parsing errors encountered")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Extraction confidence score")
    custom_fields: Dict[str, Any] = Field(default_factory=dict, description="Unmapped or vendor-specific attributes")


class BaseParser(ABC):
    """
    Abstract base class for all modular ULPF log parsers.
    """
    parser_id: str
    parser_version: str = "1.0.0"
    supported_formats: List[str] = []

    @abstractmethod
    def can_parse(self, payload: str, metadata: Optional[Dict[str, Any]] = None) -> bool:
        """
        Determines whether this parser can process the provided raw log.
        """
        pass

    @abstractmethod
    def parse(self, payload: str, metadata: Optional[Dict[str, Any]] = None) -> ParsedEvent:
        """
        Extracts structured attributes from raw payload.
        Never raises uncaught exceptions on malformed input; returns ParsedEvent with errors/warnings.
        """
        pass
